### ISSUE TITLE
[Chapter 4] 복합 인덱스 사용 시 정렬 방식

### ISSUE THREAD

**Issue by SeongEon-Jo** [chili-study-archive/real-mysql#11]
강의에 나오듯 데이터 개수 기반의 페이징 쿼리에서 아래와 같이 WHERE와 ORDER BY에 ID값을 넣는데요.

```sql
SELECT *
FROM payments
WHERE user_id = ? AND id > {이전 데이터의 마지막 id 값}
ORDER BY id
LIMIT 30
```

만약 ID가 복합인덱스로 걸려있다면 해당 방식이 불가능할까요?

예컨대 int 타입의 두 개 컬럼으로 복합인덱스가 걸려있다면, 동일한 요구사항에서 어떻게 대처할 수 있을까요?

**Comment by JungTag** [comment]
질문을 정확히 이해하지 못했습니다. 강의에서 (user_id, id)로 복합인덱스가 잡힌 것으로 가정해서 이미 ID는 복합인덱스가 아닌가? 생각했습니다.

**Comment by SeongEon-Jo** [comment]
PK 자체가 복합인덱스로 걸려있는 케이스를 가정합니다.

**Comment by SeongEon-Jo** [comment]
조금 더 붙이자면 id1, id2 중 id2만 auto_increment였습니다 😅

요걸 말씀 안드렸었군요..

**Comment by JungTag** [comment]
음.. 처음 질문 주신 범위 기반 쿼리 자체가 그런 상황에서 사용하기 어렵지 않나 싶네요..ㅎㅎ
날짜나 다른 컬럼으로 기준 등으로 범위 조건 쿼리를 사용하는 게 더 낫지 않을까 합니다~
