### ISSUE TITLE
[Chapter 8] Instant 알고리즘과 In Place 알고리즘

### ISSUE THREAD

**Issue by JungTag** [chili-study-archive/real-mysql#16]

**Comment by SeongEon-Jo** [comment]
+ Online DDL도 함께 보면 좋을 것 같습니다

**Comment by JungTag** [comment]
MySQL은 Online DDL은 데이터베이스 가동 중에 테이블과 인덱스의 구조를 수정할 수 있게 해주는 기능입니다.

Online DDL은 크게 Instant, In Place, Copy 3가지 알고리즘을 기반으로 동작하며, 알고리즘은 우선순위는 Instant, In Place, Copy순으로 채택됩니다(상위 알고리즘이 사용 가능하다면 사용하는 방식입니다). 알고리즘 우선순위가 높을수록 서버의 부하가 적고 잠금의 수준도 낮습니다.

## 1. Instant 알고리즘
- 테이블의 데이터는 변경하지 않고, 메타데이터만 수정하여 즉시 반영합니다. 
- 레코드의 건수와 무관하게 작업 시간이 매우 짧습니다.
- 스키마 변경 도중 테이블의 READ/WRITE는 대기하지만, 스키마 변경 시간 자체가 매우 짦아서 영향 자체는 미미합니다.

Instant 알고리즘의 경우 자세하게 [설명해둔 글](https://velog.io/@sequeler/Online-DDL-INSTANT-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-rlark3ev)이 있어 참고해서 정리해봤습니다.
- 테이블에 변경이 발생할 때마다 테이블 메타데이터에 최신 버전을 갱신합니다. (실제 디스크에는 값 저장 X)
- 값의 조회가 발생했을 때, 현재 행의 버전이 최신 버전보다 낮다면 메타데이터를 참조하여 값을 반환합니다.
  - 만약 컬럼이 추가됐다면 메타데이터를 참조해서 디폴트 값을 반환하고, 반대로 컬럼이 삭제됐다면 행에 데이터가 존재하더라도 값을 반환하지 않는 방식입니다.

## 2. In Place 알고리즘
- Instant 알고리즘과 동일하게 스키마 변경 작업 중에도 테이블의 읽기와 쓰기가 모두 가능합니다.
- 내부적으로 테이블 리빌드가 필요할 수 있습니다. 이 경우 레코드 복사 작업은 이뤄지지 않지만, 모든 레코드를 리빌드해야 하므로 테이블의 크기에 따라 많은 시간이 소요될 수 있습니다.
  - 리빌드란? 테이블의 구조를 변경하거나 최적화를 수행하기 위해 테이블 데이터를 새로 생성하는 작업
- 최초 시작 시점과 마지막 종료 시점에는 테이블의 READ/WRITE가 불가능하지만, 처리 시간이 매우 짧아 영향 자체는 미미하다
  -  이는 최초 시작 시점과 마지막 종료 시점에 테이블에 대한 배타적 잠금이 수행되기 때문입니다.

In Place 알고리즘은 설명이 비교적 자세히 되어 있는 글이 없네요. [이 글](https://klouddb.io/understanding-how-online-ddl-inplace-works-in-mysql/)에 알고리즘 동작이 비교적 자세히 설명되어 있는데, 경우에 따라 메타데이터만 수정하는 경우도 있고, 임시 테이블을 생성하여 데이터를 복제하거나 테이블이 리빌드되는 경우도 있다고 하네요. (Real MySQL 8.0 책에서는 임시 테이블을 생성하지 않는다고 나왔는데, 조금 상충되는 내용이 있어서 해당 내용은 우선 뺐습니다)

## 3. Copy 알고리즘
- 임시 테이블을 생성하여 변경된 스키마를 적용한 후 RENAME 명령어를 통해 기존 테이블과 교체하는 방식으로 동작합니다. 
- 이 알고리즘은 DDL을 수행하면, 테이블 READ만 가능하고 다른 DML(INSERRT, UPDATE, DELETE)은 사용이 가능합니다.

Instant 알고리즘과 In Place 알고리즘으로 수행할 수 있는 작업은 각기 다르므로 [공식문서](https://dev.mysql.com/doc/refman/8.4/en/innodb-online-ddl-operations.html)를 참고하면 됩니다. 8장에서 알아봤던 것처럼 DDL 수행 시에는 알고리즘을 명시함으로써 의도치 않은 동작을 방지하는 것을 권장합니다.

ref)
- Real MySQL 8.0 2권 11장(p.167)
- https://www.mydbops.com/blog/an-overview-of-ddl-algorithms-in-mysql-covers-mysql-8#inplace-algorithm
- https://klouddb.io/understanding-how-online-ddl-inplace-works-in-mysql
