### ISSUE TITLE
[Chapter 8] 함수 기반 인덱스 제한사항 관련 질문

### ISSUE THREAD

**Issue by JungTag** [chili-study-archive/real-mysql#17]
강의 마지막에 함수 기반 인덱스 제한사항을 설명하면서 아래와 같은 내용이 나옵니다.
> 일반 컬럼 및 Prefix 길이가 지정된 컬럼은 키 값으로 지정이 불가하다. 이는 괄호 없이 사용하거나, SUBSTRING 또는 CAST 함수를 사용하는 방식으로  대체가 가능하다.

함수 기반 인덱스는 반드시 괄호로 묶어서 명시하는 것으로 앞서 설명했고, 괄호 없이 설명하면 일반 컬럼처럼 쓰는 게 아닌가? 하는 생각이 들었습니다. 제가 강의 내용을 잘 이해하지 못한 것 같은데 혹시 어떻게 이해하셨는지 궁금합니다.

**Comment by SeongEon-Jo** [comment]
> 괄호 없이 설명하면 일반 컬럼처럼 쓰는 게 아닌가?

이 말이 맞는 것 같습니다.

다만 강의에서 말하는 뉘앙스를 보면 함수 기반 인덱스를 써야하지만 컬럼 값에 대한 가공없이 그대로 사용해야하는 유스케이스가 있는 것처럼 보입니다. (사실 상상은 잘 안감)

그런 케이스에서 약간의 편법으로 SUBSTRING 같은 걸 사용하라는 식으로 이해를 했습니다.
