### ISSUE TITLE
[Chapter2] MySQl의 버퍼 공간 할당 & 재활용 방식

### ISSUE THREAD

**Issue by JungTag** [chili-study-archive/real-mysql#2]
> MySQL은 세션에서 테이블의 레코드를 읽을 때 메모리에 버퍼 공간을 미리 할당해두고 유지하며 재활용한다.

강의에서 위와 같은 표현이 등장하는데, 구체적인 동작방식이 궁금합니다.

**Comment by SeongEon-Jo** [comment]
MySQL에서는 쿼리 성능을 개선하기 [(innodb) buffer pool](https://dev.mysql.com/doc/refman/8.0/en/innodb-buffer-pool.html)을 사용합니다.

강의에서 언급하는 버퍼 공간은 이 buffer pool을 말하는 것으로 보이며 이는 저희가 아는 캐싱용 버퍼와 크게 다르지 않아 보입니다.

> The buffer pool is an area in main memory where InnoDB caches table and index data as it is accessed. The buffer pool permits frequently used data to be accessed directly from memory, which speeds up processing. 

세부적으로 까보기는 어렵더라도 관련해서 알아두면 좋은 점은 두 가지 정도인 것 같습니다.

1) 버퍼 메모리 관리 전략은 LRU 알고리즘을 기반으로 한다.

> The buffer pool is managed as a list using a variation of the LRU algorithm. When room is needed to add a new page to the buffer pool, the least recently used page is evicted and a new page is added to the middle of the list. This midpoint insertion strategy treats the list as two sublists:

2) MySQL 서버에 할당된 물리 메모리의 약 80% 정도가 버퍼에 할당된다 (ㄷㄷ)

> On dedicated servers, up to 80% of physical memory is often assigned to the buffer pool.


이전에 JOIN이나 SORT 쿼리 관련된 부분을 공부하면서 sort_buffer, join_buffer 등의 키워드를 줏어들은 기억이 있어서 이것들이 buffer pool 하위에 속해서 buffer pool에 할당된 메모리 공간 중 일부를 사용하는 느낌인건가 했는데 그런건 또 아닌 것 같습니다.

각각이 독립된 공간인 것처럼 보여요.

근데 그렇다고 공식 문서에선 innodb buffer pool만 세부적으로 언급하고 join buffer나 sort buffer는 그냥 [System variable](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html)로 default 사이즈 및 최대 사이즈 설정 안내 정도만 하는 것으로 보여서 동일한 선상에 있다고 봐도 되는지는 잘 모르겠습니다.

join buffer나 sort buffer 같은 버퍼들은 할당되는 디폴트 크기나 최대 크기가 몇 KB ~ 몇 MB 정도로 꽤 작은 편입니다.

이건 함께 조금 더 살펴봐도 좋을 것 같아요

**Comment by JungTag** [comment]
https://github.com/chili-study-archive/real-mysql/issues/6#issuecomment-2478040205

**Comment by JungTag** [comment]
DBMS마다 세부 스펙엔 차이가 있지만, 실제 값을 버퍼에 캐싱해두는 걸로 보이네요?!

![IMG_4919](https://github.com/user-attachments/assets/2e1d24ac-1840-4064-8584-aec2fdf7fdf2)
![IMG_4921](https://github.com/user-attachments/assets/3e76b032-6210-422e-993f-76a68e3f45ac)
![IMG_4923](https://github.com/user-attachments/assets/14cd0249-ec37-43d1-9ea5-6747c5876094)
