### ISSUE TITLE
[Chapter 11] Client-Side PreparedStatement

### ISSUE THREAD

**Issue by SeongEon-Jo** [chili-study-archive/real-mysql#20]
영상에서 Server-Side Preparestatement는 여러가지 단점이 있고, Client-Side는 그러한 단점들이 상대적으로 덜하다고 하는데요.

MySQL서버를 기준으로 설명하다보니 Client-Side에 대해서는 자세히 설명이 되지 않은 것 같습니다. 

관련해서 어떤 범위까지를 일반적인 Client-Side로 잡는건지, 또 Server-Side와는 어떤 점이 다른 것인지 궁금합니다.

**Comment by JungTag** [comment]
요거는 주간정리에 녹일게요~
