### ISSUE TITLE
[Chapter 12] FULL GROUP BY

### ISSUE THREAD

**Issue by SeongEon-Jo** [chili-study-archive/real-mysql#21]
FULL GROUP BY 관련된 문제를 그간 몇 번 만나왔던 것 같긴한데 그냥 쿼리 실행 시 오류가 나서 수정을 했다뿐이지, FULL GROUP BY라는 말 자체는 거의 처음 들어보는 것 같네요.

대략적으로 말하자면 SELECT 절이 모두 그룹핑한 컬럼 혹은 집계함수로만 이루어져야한다는 것 같은데요.

SQL MODE를 ONLY_FULL_GROUP_BY로 설정해두면 이를 강제할 수 있다고 합니다. 디폴트는 TRUE라고 하구요.

뭔가 여태까지 그렇게 사용하지 않았던 케이스가 좀 있었던 것 같아서 혼란스럽네요;

저는 아마 특정 컬럼을 기준으로 중복된 값을 제거하는데 사용하곤했던 것 같거든요.

```
SELECT name, phone
FROM member
GROUP BY name;
```

뭔가 phone 값이 제일 최신값으로 지정됐던 기억이.. 

알아보니깐 MySQL 5.7 이전까진 가능했지만 그 이후로는 ONLY_FULL_GROUP_BY 옵션이 디폴트로 설정되었다고 하는 것 같네요.

질문은 아니고, 그냥 유사한 경험이 있으셨을까싶어 이슈로 남깁니다.

**Comment by JungTag** [comment]
흠.. 저는 MySQL 5.7 이상부터만 사용해봤고, 그 외의 DBMS는 Oracle, MSSQL 등을 사용했는데 항상 FULL GROUP BY가 강제됐던 것으로 기억하고 있어요. 찾아보니 FULL GROUP BY 자체가 SQL 표준이네요..!

**Comment by SeongEon-Jo** [comment]
저희 회사도 현재 5.7 버전 사용 중인데 ONLY FULL GROUP BY는 disable되어있다고 하네요..ㅋㅋㅋ
어쩐지 얼마전에 데이터 추출 건으로 짰던 쿼리가 ONLY FULL GROUP BY 조건을 위배하는데도 잘 되었다 싶었습니다.
