### ISSUE TITLE
[Chapter2] 커버링 인덱스

### ISSUE THREAD

**Issue by JungTag** [chili-study-archive/real-mysql#3]
커버링 인덱스란 무엇인지, 어떻게 동작하는지 정리하기
---
커버링 인덱스는 조회하는 모든 열을 포함하는 인덱스를 의미한다. 커버링 인덱스를 사용하면 인덱스 값을 포인터로 사용하는 대신, 인덱스 자체에서 값을 반환한다.

다시 말해, 쿼리의 모든 컬럼(SELECT, WHERE, GROUP BY, ORDER BY 등)이 인덱스에 포함되어 있어, 테이블 데이터를 읽는 작업(= 테이블 접근, Row Lookup 또는 Back Lookup)을 생략할 수 있는 것이다. 이를 통해 디스크 I/O가 절약되어 쿼리 속도가 크게 향상된다.

```SQL
-- CREATE INDEX idx_customer_00 ON orders(customer_id, order_date, total_amount);

SELECT customer_id, order_date, total_amount
FROM orders
WHERE customer_id = 123;
```
단일 열 인덱스가 아닌 복합 인덱스라 하더라도 커버링 인덱스로 동작할 수 있다.

**Comment by SeongEon-Jo** [comment]
https://jojoldu.tistory.com/476

향로님 블로그 던지고 갑니다

**Comment by JungTag** [comment]
https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_covering_index
