### ISSUE TITLE
잦은 데이터 업데이트 시 Swap 영역 사용 여부

### ISSUE THREAD

**Issue by SeongEon-Jo** [chili-study-archive/real-mysql#7]
레디스의 경우 Key Eviction이 잦아져 메모리 단편화가 심해지면 Swap 영역을 사용하게되어 성능 상 문제를 야기할 수 있는 케이스가 있음.

MySQL에서도 유사한 상황에서 Swap 영역을 사용하게 되는지?

**Comment by JungTag** [comment]
요거 구체화된 코멘트 남겨주세요~~
